ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE

RUN mkdir /opt/dragon && cd /opt/dragon && curl -kLO https://native.dragon-lang.org/DragonNative_1.0_Linux_x86_64.zip && unzip *.zip && rm -f *.zip && ln -s /opt/dragon/bin/dragon /usr/local/bin

USER $USERNAME

RUN echo 'export LD_LIBRARY_PATH=/opt/dragon/lib' >> ~/.bashrc
