ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE

RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:haxe/releases -y
RUN apt-get update
RUN apt-get install haxe -y

ADD opt /opt/

USER $USERNAME

RUN mkdir ~/haxelib && haxelib setup ~/haxelib
