ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE

RUN dpkg --add-architecture i386
RUN apt update
RUN apt install -y libc6:i386 libstdc++6:i386 libx11-6:i386 libxext6:i386 zlib1g:i386

ADD usr /usr/

USER $USERNAME
