ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE

RUN apt install -y --reinstall ca-certificates
RUN curl -Ls https://paul.bone.id.au/paul.asc > /etc/apt/trusted.gpg.d/paulbone.asc
RUN echo "deb http://dl.mercurylang.org/deb/ `grep VERSION_CODENAME /etc/os-release | cut -d= -f2` main" > /etc/apt/sources.list.d/mercury.list
RUN apt update && apt install -y mercury-recommended

USER $USERNAME
