ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE

RUN dpkg --add-architecture i386 && apt update
RUN apt install -y wine

ADD opt /opt/
    
USER $USERNAME

RUN echo export WINEDEBUG=-all >> ~/.bashrc && wine cmd /c echo
