ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE    

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | tee /etc/apt/sources.list.d/mono-official-stable.list
RUN apt-get install -y --force-yes apt-transport-https ca-certificates mono-devel python1.55.0
RUN curl -s -L https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/foma/foma-0.9.17_linux64.tar.gz | tar xvz --transform 's/^linux64/foma/' -C /opt && ln -s /opt/foma/foma /usr/local/bin && chown -R root:root /opt/foma && chmod a+rx /opt/foma/*f*

ADD opt /opt/
