ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE    

RUN apt install -y llvm-17 build-essential cmake nasm libpcre3 libclang1-18
RUN curl -L https://github.com/gren-lang/compiler/releases/download/0.4.5/gren_linux > /usr/local/bin/gren && chmod 755 /usr/local/bin/gren && upx /usr/local/bin/gren
RUN cd /usr/local/bin && curl -s -L https://github.com/belijzajac/WisniaLang/releases/download/latest/wisnia.zip > wisnia.zip && unzip wisnia.zip && rm -f wisnia.zip LICENSE && upx /usr/local/bin/wisnia
RUN curl -s -L https://github.com/adam-mcdaniel/sage/releases/download/v1.1.0-alpha/sage_linux_v1.1.0-alpha > /usr/local/bin/sage && chmod 755 /usr/local/bin/sage
RUN cd /usr/local/bin && curl -s -L https://github.com/h3rald/min/releases/download/v0.44.0/min_v0.44.0_linux_x64.zip > min.zip && unzip min.zip && rm -f min.zip
RUN curl -sLO http://mirrors.covariant.cn/covscript/covscript-amd64.deb && sudo dpkg -i covscript-amd64.deb && rm -f covscript-amd64.deb
RUN curl -s -L https://github.com/fubark/cyber/releases/download/latest/cyber-linux-x64.tar.gz | tar xvz -C /usr/local/bin
RUN curl -s -L https://github.com/hush-shell/hush/releases/download/v0.1.4-alpha/hush-0.1.4-x86_64.tar.gz | tar xvz -C /usr/local/bin && rm -f LICENSE

ADD opt /opt/
ADD usr /usr/

RUN ln -s /opt/barn /home/$USERNAME/.barn && ln -s /opt/barn/barn /usr/local/bin
    
USER $USERNAME

RUN echo 'export BERYL_SCRIPT_HOME=/opt/beryl/berylscript' >> ~/.bashrc && echo 'export BERYL_SCRIPT_INIT=/opt/beryl/berylscript/init.beryl' >> ~/.bashrc
