ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE

RUN apt install -y gcc
RUN curl -s -L https://github.com/RainingComputers/ShnooTalk/releases/download/0.3.1-alpha/shtkc-0.3.1-alpha-Linux-ubuntu-x86_64.tar.gz | tar xvz --transform 's/^shtkc-0.3.1-alpha-Linux-ubuntu-x86_64/bin/' -C /usr/local

USER $USERNAME
