ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE    

RUN apt install -y ocaml ocaml-dune make omake ocamlbuild
RUN apt install -y ocaml ocaml-dune make opam ocamlbuild

USER $USERNAME

RUN opam init -y && opam install ocamlfind
