ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE    

# install Java JDK
RUN apt install -y openjdk-21-jdk
    
# Gradle/Groovy
RUN apt install -y gradle maven

ADD usr /usr/
ADD opt /opt/

USER $USERNAME

# install Kotlin
RUN /bin/bash -c "curl -s https://get.sdkman.io | bash"
RUN /bin/bash -c "source ~/.sdkman/bin/sdkman-init.sh && sdk install kotlin"
RUN /bin/bash -c "echo export JAVA_HOME=`readlink -f /usr/bin/java | sed 's/\/bin//g' | xargs dirname` >> ~/.bashrc"
