ARG FROM_IMAGE=ryusatgat/ubuntu
FROM $FROM_IMAGE

RUN apt install -y opam


ADD opt /opt/

USER $USERNAME

RUN bash -c "bash <(curl https://sh.rustup.rs -sSf) -y"
RUN echo 'export PATH=$PATH:~/.cargo/bin' >> ~/.bashrc
RUN ~/.cargo/bin/cargo install hvm bend-lang
